USE escola;

SELECT COUNT(*) FROM BOLETINS;
SELECT SUM(NOTA) FROM BOLETINS;
SELECT MAX(NOTA) FROM BOLETINS;
SELECT MIN(NOTA) FROM BOLETINS;
SELECT AVG(NOTA) FROM BOLETINS;

SELECT ALUNO FROM BOLETINS
GROUP BY ALUNO;

SELECT ALUNO, COUNT(*), SUM(NOTA) FROM BOLETINS
GROUP BY ALUNO;

SELECT ALUNO, SUM(NOTA) NOTAS FROM BOLETINS
GROUP BY ALUNO;

SELECT ALUNO, AVG(NOTA) MÉDIA, DISCIPLINA
FROM BOLETINS
GROUP BY ALUNO, DISCIPLINA
ORDER BY ALUNO;




